# -*- coding: utf-8 -*-
"""Acamp. Python_23-03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JP1_Tr4TJNmT9--M2wb2A2ROoE9l_w6t
"""

print("Olá, de volta ao acampamento Python") #jogo da velha, em python, é utilizado para inserir comentários
print(2+2)
print(2*3/(4/5)+9**3)
print("Olá eu tenho 34 / 2 laranjas \n") #para saltar uma linha utilizar \n, sempre dentro das ""

print('O resultado da operação 9**3 =', 9**3, "e o valor de 9**4 =", 9**4)

"""O objetivo é construir um algoritimo que calcula a velocidade de um corpo dados seu deslocamento e o tempo"""

x = 30 #x é o nome da variável e 30 é o seu valor ou conteúdo
nome = "Sarah" #atribuir a variável nome  valor sarah ou então nome recebe sarah
#nome de variável NÃo pode ter espaço, acento, caracter especial
var_1 = 123.8 #TEM que usar ponto e não a vírgula
print(var_1)

dist = 30.2e6 #30.2 vezes 10 elevado a 6
tempo = 6.87
vel = dist/tempo
print("A velocidade do corpo é de", vel, "m/s")
#para retirar as casas decimais vamos usar formatação de strings
print(f"A velocidade do corpo é de {vel:.2e} m/s") #{string formatada} variável seguido de dois pontos depois ponto e o número f(float) para reduzir a quantidade de número depois do ponto

import math

print(math.cos(math.radians(33)))
print(f"o fatorial de 12 é {math.factorial(12)}")

#Crie um algoritmo em Python que execute as seguintes tarefas:

#Armazene em uma variável a quantidade de dias em um ano (não bissexto);
#Calcule e armazene em outra variável a quantidade de horas em um ano;
#Calcule e armazene em outra variável a quantidade de minutos em um ano;
#Calcule e armazene em outra variável a quantidade de segundos em um ano;

#Mostre na tela uma mensagem do tipo

#Um ano tem ... dias, ... horas, ... minutos e ...segundos;

dias = 365
horas = dias*24
minutos = horas*60
segundos = minutos*60
print(f"Um ano tem {dias} dias, {horas} horas, {minutos} minutos e {segundos} segundos")

#O IMC é calculado como IMC = peso/altura2
#vamos usar float() para converter para decimal
#vamos usar int() para converte para inteiro
peso = float(input("Digite o seu peso: "))
altura = float(input("Digite a sua altura: "))
IMC = peso/altura**2
print(f"O seu IMC é: {IMC:.2f}")

"""Vamos calcular agora o índice de massa corporal"""

#Crie um algoritmo em Python que solicite ao usuário para digitar o valor total de uma compra de supermercado.
#Depois peça ao usuário para digitar (separadamente) a quantidade de notas de 50, 20, 10 e 5 reais fornecidas pelo cliente.
#Por fim o algoritmo deve mostrar o valor do troco a ser dado ao cliente

#Veja exemplo de execução ao lado. (valores em vermelho são digitados pelo usuário)

total_compra = float(input("Digite o valor da compra: R$ "))
notas_50 = int(input("Digite a quantidade de notas de R$50: "))
notas_20 = int(input("Digite a quantidade de notas de R$20: "))
notas_10 = int(input("Digite a quantidade de notas de R$10: "))
notas_5 = int(input("Digite a quantidade de notas de R$5: "))

total_pago = 50*notas_50 + 20*notas_20 + 10*notas_10 + 5*notas_5
troco = total_pago -total_compra

if troco >=0:
  print(f"O valor da compra foi R${total_compra:.2f} o total pago foi R${total_pago:.2f} o troco é de R$ {troco:.2f}")
else:
  print(f"A compra foi R${total_compra:.2f} o total pago foi R${total_pago:.2f} valor insufucuete")

#objetico: calcular raiz quadrada
import math

x = float(input("Digite um número real: "))

if x>= 0: #se x for maior que 0 faça o que está a seguir
  y = math.sqrt(x) #math.sqrt() tira a rais quadrada
  print("A rais é: ", y)
else:
  print("Não exite raiz de número negativo")

val_et = float(input("Digite o valor do álcool R$: "))
val_gas = float(input("Digite o valor da gasolina R$: "))

perc = (val_et/val_gas)*100
print(perc,"%")

if perc >70:
  print(f"O preço do etanol está {perc:.1f}% do preço da gasolina. Abasteça com Gasolina")
else:
  print(f"Abasteça com álcool")

n1 = float(input("Digite a nota da primeira prova: "))
n2 = float(input("Digite a nota da segunda prova: "))
n3 = float(input("Digite a nota da terceira prova: "))
freq = float(input("Digite a frequência(5): "))
media = (n1+n2+n3)/3

print(f"Sua média foi de: {media:.1f} e a frequência foi {freq:.1f}")

if media >=70 and freq >=75:
  print("Você foi aprovado")
else:
  print("Você foi reprovado")

print("Sergio" > "Luana")

n1 = input("Digite o primeiro nome: ")
n2 = input("Digite o segundo nome: ")
n3 = input("Digite o terceiro nome: ")

if n1 <= n2 and n2 <= n3:
  print("Está em ordem alfabetica")
else:
  print("Não está em ordem alfabetica")

n1 = float(input("Digite a nota da primeira prova: "))
n2 = float(input("Digite a nota da segunda prova: "))
n3 = float(input("Digite a nota da terceira prova: "))
freq = float(input("Digite a frequência(%): "))
media = (n1+n2+n3)/3

print(f"Sua média foi de: {media:.1f} e a frequência foi {freq:.1f}")

if freq < 75:
  print("Aluno reprovado por frequência.")
elif media < 40:
  print("Você foi reprovado com conceito 'E'")
elif media < 70:
  print("Exame especial, conceito 'D'")
elif media < 80:
  print("Você está aprovado, conceito 'C'")
elif media < 90:
  print("Você está aprovado, conceito 'B'")
else:
  print("Supra sumo, conceito 'A'")

jog1 = input("Jogador 1 digite r,t ou p: ")
jog2 = input("Jogador 2 digite r,t ou p: ")

pedra = 'r'
tesoura = 't'
papel = 'p'

if jog1 == 'r' and jog2 == 't':
  print("Jogador 1 venceu")
elif jog1 == 'r' and jog2 == 'p':
  print("Jogador 2 ganhou.")
elif jog1 == 't' and jog2 == 'p':
  print("Jogador 1 ganhou")
elif jog1 == 't' and jog2 == 'r':
  print("Jogador 2 ganhou")
elif jog1 == 'p' and jog2 == 'r':
  print("Jogador 1 ganhou")
elif jog1 == 'p' and jog2 == 't':
  print("Jogador 2 ganhou")
elif jog1 == jog2:
  print("Deu empate")
else:
  print("Símbolos inválidos foram digitados")

import random

print("Vou sortear um número entr 1 e 20...")
print("Tente adivinhá-lo")

sorteio = random.randint(1,20) #o sorteio está antes do while
palpite = 21 #apenas para farantir que é diferente

while (sorteio != palpite): #ele repete tudo que esta na tabulação enqianto o teste dor verdadeiro
  palpite = int(input("Qual o seu palpite? "))
  if sorteio == palpite:
    print("Acertou!!")
  else:
    if(palpite > sorteio):
      print("Erriu para mais...Tente de novo...")
    else:
      print("Errou para menos...Tente de novo...")

import random

print("Vou sortear um número entr 1 e 20...")
print("Tente adivinhá-lo")

sorteio = random.randint(1,20) #o sorteio está antes do while
palpite = 21 #apenas para farantir que é diferente

while (palpite != sorteio): 
  palpite = int(input("Qual o seu palpite? "))
  if sorteio == palpite:
    print("Acertou!!")
    break #Para a exexução do while sem fazer testes
  else:
    if(palpite > sorteio):
      print("Erriu para mais...Tente de novo...")
    else:
      print("Errou para menos...Tente de novo...")

x = 1
while(x < 100):
  print(x)
  x = x + 1

valor = int(input('Para qual número você deseja a tabuada? '))  
tabuada = 0  
  
while(tabuada <= 10): 
  print(f'{valor} X {tabuada} = {valor * tabuada}')
  #print('{0} X {1} = {2}'.format(tabuada, valor, (tabuada * valor)))  
  tabuada = tabuada + 1

c1 = 0
c2 = 0
c3 = 0
voto = 0
nulo = 0

while(voto != -1):
  voto = int(input("Digite o seu voto: "))
  if voto == 1:
    c1 = c1 + 1
  elif voto == 2:
    c2 = c2 + 1
  elif voto == 3:
    c3 = c3 + 1
  elif voto == -1:
    pass
  else:
    nulo = nulo + 1

print("Resultado das eleições!")
if c1 == c2 and c1 > c3 or c1 == c3 and c1 > c2 or c2 == c3 and c2 > c1:
  print("Temos um empate.")
elif c1 > c2 and c1 > c3:
  print("Candidato 1 ganhou!")
elif c2 > c1 and c2 > c3:
  print("Candidato 2 ganhou!")
elif c3 > c1 and c3 > c2:
  print("Candidato 3 ganhou!")
else:
  print("O nulo ganhou temos que anular a eleição.")

#Vamos aprender o loop ou laço "for"

for var in range(1,10):
  print (var)

n = int(input("Qual é a tabuada?"))
for j in range(1,11): 
  print(f'{n} x {j} = {n*j}')

s0 = float(input("Digite a posição inicial."))
v = float(input("Digite a velociada: "))
print("Tabela posição x tempo para este móvel")
print("Tempo(s)---Posição(m)")
for t in range(0,26):
  print(f"{t:8.2f}---{s0 + v*t:10.2f} ") #para alinhar os números (< alinhar esquerda > alinhar a direito ^ centralizar)

import random

n = int(input("Quantas dezenas deseja sortear? "))

for i in range(1,n+1):
  x = random.randint(1,25)
  print(f"{x} ",end = "")

xl = [] #criei uma lista

xl.append(1) #append quer dizer adicionar ao final
xl.append(21)
xl.append(309.5)

print(xl)
xl.append(1.2e-8)

print(xl)

print(xl[3])

xl.append("Uma string!")

print(xl)

import random

n = int(input("Quantas dezenas deseja sortear?"))
print("Sorteei para você os seguintes números.")

sorteio = []

for i in range(0,n):
  x = random.randint(1,60)
  while x in sorteio:
    x = random.randint(1,60)
  sorteio.append(x)

print(sorted(sorteio))

"""# Nova seção"""



print("Olá, de volta ao acampamento Python") #jogo da velha, em python, é utilizado para inserir comentários
print(2+2)
print(2*3/(4/5)+9**3)
print("Olá eu tenho 34 / 2 laranjas \n") #para saltar uma linha utilizar \n, sempre dentro das ""

print('O resultado da operação 9**3 =', 9**3, "e o valor de 9**4 =", 9**4)

"""O objetivo é construir um algoritimo que calcula a velocidade de um corpo dados seu deslocamento e o tempo"""

x = 30 #x é o nome da variável e 30 é o seu valor ou conteúdo
nome = "Sarah" #atribuir a variável nome  valor sarah ou então nome recebe sarah
#nome de variável NÃo pode ter espaço, acento, caracter especial
var_1 = 123.8 #TEM que usar ponto e não a vírgula
print(var_1)

dist = 30.2e6 #30.2 vezes 10 elevado a 6
tempo = 6.87
vel = dist/tempo
print("A velocidade do corpo é de", vel, "m/s")
#para retirar as casas decimais vamos usar formatação de strings
print(f"A velocidade do corpo é de {vel:.2e} m/s") #{string formatada} variável seguido de dois pontos depois ponto e o número f(float) para reduzir a quantidade de número depois do ponto

import math

print(math.cos(math.radians(33)))
print(f"o fatorial de 12 é {math.factorial(12)}")

#Crie um algoritmo em Python que execute as seguintes tarefas:

#Armazene em uma variável a quantidade de dias em um ano (não bissexto);
#Calcule e armazene em outra variável a quantidade de horas em um ano;
#Calcule e armazene em outra variável a quantidade de minutos em um ano;
#Calcule e armazene em outra variável a quantidade de segundos em um ano;

#Mostre na tela uma mensagem do tipo

#Um ano tem ... dias, ... horas, ... minutos e ...segundos;

dias = 365
horas = dias*24
minutos = horas*60
segundos = minutos*60
print(f"Um ano tem {dias} dias, {horas} horas, {minutos} minutos e {segundos} segundos")

#O IMC é calculado como IMC = peso/altura2
#vamos usar float() para converter para decimal
#vamos usar int() para converte para inteiro
peso = float(input("Digite o seu peso: "))
altura = float(input("Digite a sua altura: "))
IMC = peso/altura**2
print(f"O seu IMC é: {IMC:.2f}")

"""Vamos calcular agora o índice de massa corporal"""

#Crie um algoritmo em Python que solicite ao usuário para digitar o valor total de uma compra de supermercado.
#Depois peça ao usuário para digitar (separadamente) a quantidade de notas de 50, 20, 10 e 5 reais fornecidas pelo cliente.
#Por fim o algoritmo deve mostrar o valor do troco a ser dado ao cliente

#Veja exemplo de execução ao lado. (valores em vermelho são digitados pelo usuário)

total_compra = float(input("Digite o valor da compra: R$ "))
notas_50 = int(input("Digite a quantidade de notas de R$50: "))
notas_20 = int(input("Digite a quantidade de notas de R$20: "))
notas_10 = int(input("Digite a quantidade de notas de R$10: "))
notas_5 = int(input("Digite a quantidade de notas de R$5: "))
total_pago = (50*notas_50 + 20*notas_20 + 10*notas_10 + 5*notas_5)
troco = total_compra - total_pago
if total_compra <= total_pago:
  print("O valor da compra foi R$", total_compra, "o total pago foi R$", total_pago, "o troco é de R$", troco)
else:
  print("O valor da compra foi R$", total_compra, "o total pago foi R$", total_pago, "completar R$", troco)